// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ritcvnhcxqxkmoixpqwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpdGN2bmhjeHF4a21vaXhwcXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDE2NjksImV4cCI6MjA2NzI3NzY2OX0.GaGK4tWomGtmlHM_DqFVbjnWK1K_m49PNsiiZAKOJ00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});